# Generated by Django 3.2.8 on 2022-10-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0003_alter_audiofile_binary_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='binary_data',
            field=models.FileField(upload_to=''),
        ),
    ]
