# Generated by Django 3.2.8 on 2022-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0007_alter_audiofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
