# Generated by Django 3.2.8 on 2022-10-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiofiles', '0008_alter_audiofile_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
